### PR TITLE
Cleanup fig2

### PR DESCRIPTION
**Pull request by k1o0**
**Please squash before merging!**

### CODE REVIEW

**Comment by juhuntenburg** [comment]
@k1o0 is this ready to be merged (if I squash)?

**Comment by k1o0** [comment]
> @k1o0 is this ready to be merged (if I squash)?

I think so yeah!

**Comment by juhuntenburg** [comment]
Hi, I see that there is a bunch of code also regarding different analyses (manifold, decoding etc)

What is the code that is actually for Yanliang's analysis? Or is all of this required for the paper? I just don't want to merge some obsolete code. 

Also, the idea was that each analysis has their own subfolder in brainwidemap that contains all code required for that analysis

**Comment by juhuntenburg** [comment]
Also I don't think that this repository is the place for results?

**Comment by k1o0** [comment]
Yanliang put his code on develop, so I branched off develop here.  The relevant files contain 'fig2':
```
./brainwidemap/fig2_single_cell_Working_example_block.py
./brainwidemap/fig2_single_cell_Working_example_choice.py
./brainwidemap/fig2_single_cell_Working_example_feedback.py
./brainwidemap/fig2_single_cell_Working_example_stimulus.py
./brainwidemap/fig2_util.py
./brainwidemap/test/fig2_block.pkl
./brainwidemap/test/fig2_data.pkl
./brainwidemap/test/fig2_stim.pkl
./brainwidemap/test/test_fig2_single_cell.py
```
I don't know what the distinction is between analysis and results, or anything about this repo's organization, I simply ran and cleaned up the code he gave me.

**Comment by juhuntenburg** [comment]
Ok great, I'll cherry pick the commits pertaining to these files then. I was referring to a folder called "results" but if that's not part of the relevant code that's great.

Thanks!

**Comment by juhuntenburg** [comment]
Merged the relevant files to main manually. Closing this

**Review by juhuntenburg — APPROVED** [review]
Removed all surplus files and renamed. Looks good for now

**Pull request merged**
